# Generated by Django 2.1.4 on 2018-12-27 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hohoho', '0002_auto_20181227_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecretSantaGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(max_length=2000)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_game', to='hohoho.SecretSanta')),
            ],
        ),
        migrations.RemoveField(
            model_name='players',
            name='user',
        ),
        migrations.RemoveField(
            model_name='players',
            name='wish',
        ),
        migrations.AddField(
            model_name='usersecretsantagame',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_player', to='hohoho.Players'),
        ),
        migrations.AddField(
            model_name='usersecretsantagame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
