# Generated by Django 2.1.4 on 2018-12-27 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hohoho', '0003_auto_20181227_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretsanta',
            name='user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersecretsantagame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
