# Generated by Django 2.1.4 on 2018-12-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hohoho', '0005_secretuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretuser',
            name='player',
        ),
        migrations.RemoveField(
            model_name='secretuser',
            name='user',
        ),
        migrations.AddField(
            model_name='usersecretsantagame',
            name='gift_to_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_users', to='hohoho.Players'),
        ),
        migrations.DeleteModel(
            name='SecretUser',
        ),
    ]
