# Generated by Django 2.1.4 on 2018-12-28 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hohoho', '0007_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='game',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='usersecretsantagame',
            name='player',
        ),
        migrations.AlterField(
            model_name='usersecretsantagame',
            name='gift_to_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
