# Generated by Django 2.1.4 on 2018-12-28 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hohoho', '0008_auto_20181228_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='secretsanta',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersecretsantagame',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersecretsantagame',
            name='gift_to_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_users', to='hohoho.UserSecretSantaGame'),
        ),
        migrations.AddField(
            model_name='rules',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_in_rule', to='hohoho.UserSecretSantaGame'),
        ),
        migrations.AddField(
            model_name='rules',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_in_rule', to='hohoho.UserSecretSantaGame'),
        ),
    ]
